"""Text handling below the tokenizer.

`utf8` decodes and encodes, strictly, and says the difference between a
sequence that is wrong and one that is only unfinished. `tables` is the Unicode
database, generated by scripts/gen-unicode.py and not written by hand. `props`
decodes those tables and answers questions about a character. `normalize` is
the four normal forms. `regex` is a backtracking matcher for the patterns that
live inside a tokenizer.json.

None of it is a general purpose string library. It exists because a tokenizer
has to make the same decisions the Rust crates behind tokenizer.json make, down
to the character, and the only way to do that is to have the same tables.
"""
