"""Writing JSON into a buffer, in the order it was written.

One buffer, appended to, with a small stack that knows whether a comma is due
and whether a key or a value comes next. Nothing is built and then copied, so a
response body is assembled once into the buffer that goes to the ring.

## Key order

Members go out in the order the caller writes them, because there is no
container in between to lose it. That is not a detail for a tool call: the
arguments object is generated by a model that saw a particular order in training
and in the schema, and an encoder that sorts keys is handing something different
to whatever runs the function. So there is no sorting, no map, and no mode flag,
and the same is true on the reading side in `dom.mojo`.

## Escaping

The escape decision is what the RFC requires and nothing more. Quote, backslash
and the C0 controls, with the six short forms where they exist and `\\u00xx`
where they do not. Not a forward slash, which needs no escape and whose escape
exists only because of a decade old habit around `</script>`. Not non ASCII,
which is UTF-8 in the output the same as it was in the input, and escaping it
would triple the size of a Japanese message for nothing.

Bytes above 0x7F are passed through as they arrived. That means the writer does
not make invalid UTF-8 valid, and the reader is where that check lives, so a
string that came from a parse is already known good and a string a caller built
by hand is the caller's business.

## Doubles

`number.mojo` does the work. What lands here is the choice of format: a plain
decimal when the exponent is small enough that one is shorter and easier to
read, and an exponent form when it is not. The cutoffs are the ones every
language settled on, because a config file full of `1e-5` where `0.00001` would
do is worse to read and a line of three hundred zeros is worse still.

A non finite double has no JSON spelling. `Infinity` and `NaN` are not in the
grammar, and writing them produces a document that a strict parser on the other
end refuses. So they are written as `null` and counted, and a non zero count is
a bug upstream worth finding.
"""

from molla.io.buffer import Buffer
from molla.json.decimal import Decimal
from molla.json.number import double_to_decimal

comptime _HEX = "0123456789abcdef"

comptime _ST_ROOT = 0
comptime _ST_ARRAY = 1
comptime _ST_OBJECT = 2

comptime WRITER_DEPTH = 128


def write_json_int(mut out: Buffer, value: Int) -> Bool:
    """Decimal into the buffer with no digit list in between."""
    if value == 0:
        return out.append_byte(UInt8(48))
    var negative = value < 0
    var n = -value if negative else value
    var width = 0
    var probe = n
    while probe > 0:
        probe //= 10
        width += 1
    var total = width + 1 if negative else width
    if not out.reserve(total):
        return False
    var at = out.length
    var p = out.ptr()
    if negative:
        p.unsafe_store(at, UInt8(45))
        at += 1
    var i = at + width - 1
    while n > 0:
        p.unsafe_store(i, UInt8(48 + n % 10))
        n //= 10
        i -= 1
    out.commit(total)
    return True


def write_json_string(mut out: Buffer, data: Span[UInt8, _]) -> Bool:
    """A quoted, escaped string.

    Runs of bytes that need nothing are appended in one call, because a message
    body is thousands of bytes with no escapes in it and appending it a byte at
    a time is the whole cost of the response.
    """
    if not out.append_byte(UInt8(34)):
        return False
    var n = len(data)
    var run = 0
    var i = 0
    while i < n:
        var c = data[i]
        if c != 34 and c != 92 and c >= 32:
            i += 1
            continue
        if i > run:
            if not out.append(data[run:i]):
                return False
        if c == 34:
            if not out.append_str('\\"'):
                return False
        elif c == 92:
            if not out.append_str("\\\\"):
                return False
        elif c == 10:
            if not out.append_str("\\n"):
                return False
        elif c == 13:
            if not out.append_str("\\r"):
                return False
        elif c == 9:
            if not out.append_str("\\t"):
                return False
        elif c == 8:
            if not out.append_str("\\b"):
                return False
        elif c == 12:
            if not out.append_str("\\f"):
                return False
        else:
            # A control byte with no short form. Six bytes, and the only place
            # this writer emits a \\u escape at all.
            if not out.append_str("\\u00"):
                return False
            var hex = _HEX.unsafe_ptr()
            if not out.append_byte(hex.unsafe_load(Int(c >> 4))):
                return False
            if not out.append_byte(hex.unsafe_load(Int(c & 15))):
                return False
        i += 1
        run = i
    if n > run:
        if not out.append(data[run:n]):
            return False
    return out.append_byte(UInt8(34))


def write_json_double(mut out: Buffer, value: Float64) -> Bool:
    """The shortest decimal that reads back as this double.

    Returns False only when the buffer will not grow. A non finite value is
    written as `null`, which the caller can also detect by asking `is_finite`
    before calling.
    """
    if value != value:
        return out.append_str("null")
    if value > 1.7976931348623157e308 or value < -1.7976931348623157e308:
        return out.append_str("null")
    if value == 0.0:
        # Signed zero survives the round trip, since -0.0 and 0.0 are different
        # doubles and a caller that produced one meant it.
        if (1.0 / value) < 0.0:
            return out.append_str("-0")
        return out.append_byte(UInt8(48))

    var dec = Decimal()
    double_to_decimal(value, dec)
    return _write_decimal(out, dec)


def _write_decimal(mut out: Buffer, dec: Decimal) -> Bool:
    if dec.negative:
        if not out.append_byte(UInt8(45)):
            return False
    if dec.nd == 0:
        return out.append_byte(UInt8(48))

    # Plain form while the exponent is small, which is what a human reads and
    # what every other encoder produces for ordinary numbers. The two cutoffs
    # are JavaScript's, so a number written here and read by a browser prints
    # the same on both sides, which is one fewer thing to argue about in a bug
    # report that has a JSON body in it.
    if dec.dp > -6 and dec.dp <= 21:
        return _write_plain(out, dec)
    return _write_exponent(out, dec)


def _write_plain(mut out: Buffer, dec: Decimal) -> Bool:
    if dec.dp <= 0:
        if not out.append_str("0."):
            return False
        for _ in range(-dec.dp):
            if not out.append_byte(UInt8(48)):
                return False
        for i in range(dec.nd):
            if not out.append_byte(UInt8(48) + dec.d[i]):
                return False
        return True
    for i in range(dec.dp):
        var digit = dec.d[i] if i < dec.nd else UInt8(0)
        if not out.append_byte(UInt8(48) + digit):
            return False
    if dec.nd <= dec.dp:
        # A whole number. Written without a trailing `.0`, since JSON has one
        # number type and a reader that wants a double gets one either way.
        return True
    if not out.append_byte(UInt8(46)):
        return False
    for i in range(dec.dp, dec.nd):
        if not out.append_byte(UInt8(48) + dec.d[i]):
            return False
    return True


def _write_exponent(mut out: Buffer, dec: Decimal) -> Bool:
    if not out.append_byte(UInt8(48) + dec.d[0]):
        return False
    if dec.nd > 1:
        if not out.append_byte(UInt8(46)):
            return False
        for i in range(1, dec.nd):
            if not out.append_byte(UInt8(48) + dec.d[i]):
                return False
    if not out.append_byte(UInt8(101)):
        return False
    var exp = dec.dp - 1
    if exp >= 0:
        if not out.append_byte(UInt8(43)):
            return False
    else:
        if not out.append_byte(UInt8(45)):
            return False
        exp = -exp
    return write_json_int(out, exp)


struct Writer(Movable):
    """A buffer and a stack that knows what comes next."""

    var out: Buffer
    var depth: Int
    var stack: InlineArray[UInt8, WRITER_DEPTH]
    var seen: InlineArray[Bool, WRITER_DEPTH]
    var expect_value: Bool
    """A key has been written and the value that goes with it has not."""

    var failed: Bool
    """One sticky flag rather than a check on every call.

    A writer builds a response with dozens of calls and checking each one turns
    every handler into an error ladder. The first failure is remembered, every
    later call is a no op, and `ok()` at the end is the one check. The only
    failure that can happen is the buffer refusing to grow, and past that point
    the body is going to be thrown away regardless.
    """

    var non_finite: Int
    """Doubles that had no JSON spelling and went out as null. Not zero means a
    NaN or an infinity got as far as the encoder."""

    def __init__(out self, counter: Int, capacity: Int = 4096):
        self.out = Buffer(capacity, counter)
        self.depth = 0
        self.stack = InlineArray[UInt8, WRITER_DEPTH](fill=0)
        self.seen = InlineArray[Bool, WRITER_DEPTH](fill=False)
        self.expect_value = False
        self.failed = False
        self.non_finite = 0

    def reset(mut self):
        """Ready for the next document, keeping the capacity. The same rule as
        the HTTP response writer, and for the same reason."""
        self.out.clear()
        self.depth = 0
        self.expect_value = False
        self.failed = False

    def ok(self) -> Bool:
        return not self.failed

    def length(self) -> Int:
        return self.out.length

    def bytes(self) -> Span[UInt8, MutAnyOrigin]:
        return self.out.bytes()

    def complete(self) -> Bool:
        """Every container opened was closed and nothing is half written.

        Worth asking before a body goes out. A response missing its last brace
        is a parse error on the client with nothing on this side to explain it.
        """
        return not self.failed and self.depth == 0 and not self.expect_value

    def _fail(mut self) -> Bool:
        self.failed = True
        return False

    def _before_value(mut self) -> Bool:
        """Comma if one is due, and refuse a value where a key belongs."""
        if self.failed:
            return False
        if self.depth == 0:
            return True
        if self.stack[self.depth - 1] == _ST_OBJECT and not self.expect_value:
            # A value directly inside an object with no key in front of it.
            return self._fail()
        if self.expect_value:
            self.expect_value = False
            return True
        if self.seen[self.depth - 1]:
            if not self.out.append_byte(UInt8(44)):
                return self._fail()
        self.seen[self.depth - 1] = True
        return True

    def _open(mut self, kind: Int, brace: UInt8) -> Bool:
        if not self._before_value():
            return False
        if self.depth >= WRITER_DEPTH:
            return self._fail()
        if not self.out.append_byte(brace):
            return self._fail()
        self.stack[self.depth] = UInt8(kind)
        self.seen[self.depth] = False
        self.depth += 1
        return True

    def _close(mut self, kind: Int, brace: UInt8) -> Bool:
        if self.failed:
            return False
        if self.depth == 0 or Int(self.stack[self.depth - 1]) != kind:
            return self._fail()
        if self.expect_value:
            # A key with no value, which would produce `{"a":}`.
            return self._fail()
        self.depth -= 1
        if not self.out.append_byte(brace):
            return self._fail()
        return True

    def begin_object(mut self) -> Bool:
        return self._open(_ST_OBJECT, UInt8(123))

    def end_object(mut self) -> Bool:
        return self._close(_ST_OBJECT, UInt8(125))

    def begin_array(mut self) -> Bool:
        return self._open(_ST_ARRAY, UInt8(91))

    def end_array(mut self) -> Bool:
        return self._close(_ST_ARRAY, UInt8(93))

    def key(mut self, name: StringSpan) -> Bool:
        return self.key_bytes(name.as_bytes())

    def key_bytes(mut self, name: Span[UInt8, _]) -> Bool:
        if self.failed:
            return False
        if self.depth == 0 or self.stack[self.depth - 1] != _ST_OBJECT:
            return self._fail()
        if self.expect_value:
            return self._fail()
        if self.seen[self.depth - 1]:
            if not self.out.append_byte(UInt8(44)):
                return self._fail()
        self.seen[self.depth - 1] = True
        if not write_json_string(self.out, name):
            return self._fail()
        if not self.out.append_byte(UInt8(58)):
            return self._fail()
        self.expect_value = True
        return True

    def null(mut self) -> Bool:
        if not self._before_value():
            return False
        if not self.out.append_str("null"):
            return self._fail()
        return True

    def bool(mut self, value: Bool) -> Bool:
        if not self._before_value():
            return False
        var text = "true" if value else "false"
        if not self.out.append_str(text):
            return self._fail()
        return True

    def int(mut self, value: Int) -> Bool:
        if not self._before_value():
            return False
        if not write_json_int(self.out, value):
            return self._fail()
        return True

    def double(mut self, value: Float64) -> Bool:
        if not self._before_value():
            return False
        var finite = (
            value == value
            and value <= 1.7976931348623157e308
            and value >= -1.7976931348623157e308
        )
        if not finite:
            self.non_finite += 1
        if not write_json_double(self.out, value):
            return self._fail()
        return True

    def string(mut self, text: StringSpan) -> Bool:
        return self.string_bytes(text.as_bytes())

    def string_bytes(mut self, data: Span[UInt8, _]) -> Bool:
        if not self._before_value():
            return False
        if not write_json_string(self.out, data):
            return self._fail()
        return True

    def raw(mut self, data: Span[UInt8, _]) -> Bool:
        """Already encoded JSON, copied in as a value with no checking.

        For a fragment that came from somewhere that already produced JSON, a
        cached tool schema being the case that matters. The caller is promising
        it is one value and that it is well formed, and nothing here can tell.
        """
        if not self._before_value():
            return False
        if not self.out.append(data):
            return self._fail()
        return True

    def field_str(mut self, name: StringSpan, value: StringSpan) -> Bool:
        return self.key(name) and self.string(value)

    def field_int(mut self, name: StringSpan, value: Int) -> Bool:
        return self.key(name) and self.int(value)

    def field_double(mut self, name: StringSpan, value: Float64) -> Bool:
        return self.key(name) and self.double(value)

    def field_bool(mut self, name: StringSpan, value: Bool) -> Bool:
        return self.key(name) and self.bool(value)

    def field_null(mut self, name: StringSpan) -> Bool:
        return self.key(name) and self.null()
